### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by KnightArch** [FuelRats/FCMS#133]
I've been trying to register for months and every time I try the registration fails. The log in form does nothing and the recover password method seems to do nothing too because it doesn't send e-mails or return any info. Tryed from many devices, browsers, OSs and different e-mail services with the same results: nothing works.

**Comment by kenneaal** [comment]
Greetings. Please provide me with a CMDR name you've been trying to register with, or send an email to absolver at fuelrats,com with an email you've attempted to register, and I'll look into that. Registration process seems to be working correctly.
