### ISSUE TITLE
Changed my name in Frontier/Ingame, Now FCMS cant recognise my FC Jumps error:400

### ISSUE THREAD

**Issue by Takaber** [FuelRats/FCMS#136]
I have a problem with FCMS i cant set jumps to show in my fleet discord cuz i recently changed name before i was [Cap] Takaber now i changed without the [] and just Cap Takaber also i did another mistake that i created another account in FCMS with my correct name Cap Takaber but i cant set my fc cuz obviously i did it with my another account with the wrong name, idk if can fix that plz delete the new account that i set and change the name or CMDR in my first account that i created plz :c
![unknown (2)](https://user-images.githubusercontent.com/51917858/116327325-88f9c200-a794-11eb-93c3-1a55b7777249.png)

**Comment by kenneaal** [comment]
Closed, not a bug. Send an email from your original account with:
* Your new CMDR name
* The new email address you registered

and we'll get that sorted.
