### ISSUE TITLE
Wrong CMDR name set it/ Delete another Account with the Correct CMDR name

### ISSUE THREAD

**Issue by Takaber** [FuelRats/FCMS#137]
Hello i have a problem i registered in FMCS with the Name of CMDR {Cap] Takaber but i changed my name to Cap Takaber in game so dont work the FCMS anymore and with trying to fix that i created another account in FCMS with the correct name Cap Takaber but obviously don't let me register my Fleet Carrier cuz its already registered with my another account and idk if can delete the second account with the correct name and correct the name for my first account CMDR [Cap] Takaber into Cap Takaber only so i can use the FCMS :c plz
![Primerfc](https://user-images.githubusercontent.com/51917858/116363226-e7dd2c80-a7d0-11eb-8c57-b27b6fc64a5b.png)
![seondfc](https://user-images.githubusercontent.com/51917858/116363244-ec094a00-a7d0-11eb-96ec-b8427db11c80.png)

**Comment by kenneaal** [comment]
See reply to your previous issue on this. I can't go in and change anything unless I can verify that you're the account owner. Send an email to the Fuel Rats support email address with your new and old commander name, and we will sort it out.

**Comment by Takaber** [comment]
Excuse me idk what is the Email address for Fuel Rats support, where i can find it?
