### ISSUE TITLE
Error: 500

### ISSUE THREAD

**Issue by Takaber** [FuelRats/FCMS#138]
Hello i have this issue i contact with fuel rats to fix my name and still have this error and idk how to fix it plz help D:
![F500](https://user-images.githubusercontent.com/51917858/116505632-5f6e9280-a889-11eb-9efe-953af44758d6.jpg)

**Comment by kenneaal** [comment]
Again, not a bug. You are providing a nonsensical URL to the webhook setting. Fix the setting in FCMS, and it'll be fine. Please note that this is for reporting bugs with the software, not requesting support.
