### ISSUE TITLE
Error Logging in

### ISSUE THREAD

**Issue by thenamesjay03** [FuelRats/FCMS#144]
![https___fleetcarrier space_my_carrier - Personal - Microsoft​ Edge 7_6_21 11_26_58 AM](https://user-images.githubusercontent.com/83084519/121001954-b8342380-c783-11eb-94e9-456bb84a85ca.png)
When I try to log in i get this error
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)

**Comment by kenneaal** [comment]
Fixed with hotfix 0a5cf15b, Odyssey changed shipyard CAPI format.
