### ISSUE TITLE
Registration Failed

### ISSUE THREAD

**Issue by WerhnerHeisenberg** [FuelRats/FCMS#172]
![image](https://github.com/FuelRats/FCMS/assets/37519343/dcaee146-18bc-4a41-b5ac-393737bf6425)
Every time I try to register my Fleet Carrier I get this message.
Sorry if this is not the right place to report this.

**Comment by Dobrowit** [comment]
I would like to register FC but I get the message: 
"Error: Your carrier seems to already be claimed by another account! Please report this.".

**Comment by kenneaal** [comment]
As the message says, your carrier is already registered under a different account. Find the original one.
