### ISSUE TITLE
TypeError: 'options' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by elgarty** [FuelRats/FCMS#175]
I keep getting this error trying to set up the website

**Comment by cattoman1** [comment]
got it working by removeing the timezone argument in the _init_.py in FCMS/FCMS/models But the website looks all weird any ideas?
![image](https://github.com/FuelRats/FCMS/assets/104154537/841da5fd-bf89-4968-9645-94dd4a9b8554)
