### ISSUE TITLE
Problems on setup

### ISSUE THREAD

**Issue by cattoman1** [FuelRats/FCMS#176]
something in these lines From _initialize_db.py_ Makes the setup error with:

> TypeError: 'options' is an invalid keyword argument for this function

```
def main(argv=sys.argv):
    args = parse_args(argv)
    setup_logging(args.config_uri)
    env = bootstrap(args.config_uri)

    try:
        with env['request'].tm:
            dbsession = env['request'].dbsession
            setup_models(dbsession)
    except OperationalError:
```

**Comment by cattoman1** [comment]
the website only run locally even if its port forwarded pls help

**Comment by kenneaal** [comment]
InitializeDB is not used with FCMS. The error is also in SQLAlchemy, not in FCMS. FCMS was coded against SQLAlchemy 1.3, later versions may have API changes that require revision.
