### ISSUE TITLE
How to setup the Fdev auth

### ISSUE THREAD

**Issue by cattoman1** [FuelRats/FCMS#177]
So i got the website HALF ISH working but when i try auth then i get this error 
![image](https://github.com/FuelRats/FCMS/assets/104154537/99022669-b7ab-4720-86bb-6be931b24a6f)
 
how and from where do i get the 
![image](https://github.com/FuelRats/FCMS/assets/104154537/357a79a3-572f-4b94-ab89-8c88fe9ca0d0)

Cant find it on [auth.frontierstore](https://auth.frontierstore.net)

![image](https://github.com/FuelRats/FCMS/assets/104154537/7c2889b5-a663-4f99-bd43-0287b2f08e9c)

how to fix that error and get Client secret not client ID

**Comment by kenneaal** [comment]
Request the correct auth flow in your developer account. The secret is the shared key, client ID is client ID.

**Comment by elgarty** [comment]
why is the shared key "inactive" how can i get that
